[profile.default]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
viaIR = true

[profile.rpc-endpoints]
somniaTestnet = "https://dream-rpc.somnia.network/"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options